language: cpp

# helpful article: https://genbattle.bitbucket.io/blog/2016/01/17/c++-travis-ci

matrix:
    include:
    - os: osx
      osx_image: xcode8.2
      compiler: clang
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7 CXX=clang++-3.7 CC=clang-3.7
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5 CXX=g++-5 CC=gcc-5

before_script:
    - cd extras
    - cd tests  
    - mkdir build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=$COMPILER ..

script: make  

