language: cpp

matrix:
    include:
    - os: osx
      osx_image: xcode8.2
    - os: linux
      compiler: clang
    - os: linux
      compier: gcc

before_script:
    - cd extras
    - cd tests  
    - mkdir build
    - cd build
    - cmake ..

script: make  

